# 선행 조건
# 1. npm run build
# 2. spring boot build
# 3. profile 설정
### 3-1. docker compose --profile dev up
### 3-2. docker compose --profile prod up

services:

  db:
    image: mysql:8.4.1
    volumes:
      - ./db_data:/var/lib/mysql # TODO: ./db_data 경로가 올바른가?
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: 'always'
    ports:
      - "8080:8080"
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    restart: 'always'
    ports:
      - "5173:5173"
    environment:
      PROFILE: ${PROFILE}
    container_name: frontend
