# 선행 조건
# 1. React build : npm run build
# 2. spring boot build : ./gradlew build
# 3. profile 설정 후  compose
### 3-1. PROFILE=dev docker compose up
### 3-2. PROFILE=prod docker compose up

services:

  db:
    image: mysql:8.4.1
    volumes:
      - ./db_data:/var/lib/mysql # TODO: ./db_data 경로가 올바른가?
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: 'always'
    ports:
      - "8080:8080"
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PROFILE: ${PROFILE}
    image: frontend
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    container_name: frontend
