# 선행 조건
# 1. profile 설정 후  compose
### 1-1. PROFILE=dev docker compose up
### 1-2. PROFILE=prod docker compose up

services:

  db:
    image: mysql:8.0.39
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: 'always'
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PROFILE: ${PROFILE}
    image: frontend
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    container_name: frontend
